version: '3.4'
services:
  mysql-hp:
    container_name: mysql-hp
    image: mysql
    volumes:
        - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/1.sql
        - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my-app-test
      - MYSQL_ROOT_PASSWORD=P4ssword!
    ports:
      - 33306:3306
  keycloak-hp:
      container_name: keycloak-hp
      image: quay.io/keycloak/keycloak:22.0.1
      command:
        - "start-dev"
        - "--hostname-port=8080"
      ports:
        - "8080:8080"
        #- "18443:8443"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_HOSTNAME: keycloak-hp
        KC_DB: mysql
        KC_DB_URL_HOST: mysql-hp
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: root
        KC_DB_PASSWORD: P4ssword!
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
      depends_on:
        - mysql-hp

  prometheus:
    image: prom/prometheus
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
        - --enable-feature=exemplar-storage
        - --config.file=/etc/prometheus/prometheus.yml
    volumes:
        - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - ./docker/prometheus/rule.yml:/etc/prometheus/rule.yml:ro
        - token_volume:/app/tokens
    ports:
        - "9090:9090"
    depends_on:
        - token_retrieval
        - mysql-hp-exporter
        - keycloak-hp
    
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./docker/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml"
    ports:
      - 9093:9093

  tempo:
    image: grafana/tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
        - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
        - tempo_data:/tmp/tempo
    ports:
        - "14268"  # jaeger ingest
        - "9411:9411" # zipkin   
  loki:
    image: grafana/loki
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
        - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
        - JAEGER_AGENT_HOST=tempo
        - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
        - JAEGER_SAMPLER_TYPE=const
        - JAEGER_SAMPLER_PARAM=1
  grafana:
    image: grafana/grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
        - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
        - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
        - "3001:3000"

  token_retrieval:
    build:
      context: .
      dockerfile: Dockerfile_token_retrieval
    volumes:
      - ./token_retrieval_script.py:/app/token_retrieval_script.py
      - token_volume:/app/tokens
    depends_on:
      - keycloak-hp

  mysql-hp-exporter:
    container_name: mysql-hp-exporter
    image: quay.io/prometheus/mysqld-exporter
    command:
     - "--mysqld.username=root:P4ssword!"
     - "--mysqld.address=mysql-hp:3306"
    #environment:
    #  DATA_SOURCE_NAME: "root:P4ssword!@(mysql-hp:3306)/" # Adjust credentials and MySQL host/port
    ports:
      - '9104:9104'
    depends_on:
      - mysql-hp


  ganache:
    image: trufflesuite/ganache-cli:latest
    command: [ "--db", "/ganache_data", "--mnemonic", "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat", "--chainId", "1337" ]
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data

#  ipfs:
#    image: ipfs/go-ipfs:latest
#    restart: always
#    ports:
#      - "4001:4001"
#      - "5001:5001"
#      - "8081:8080"
#    volumes:
#      - ipfs-data:/data/ipfs

#  storage_node:
#    image: ethereum/client-go:latest
#    environment:
#      - ETH_RPC_URL=http://ganache:8545
#      - IPFS_API_URL=http://ipfs:5001
#    depends_on:
#      - ganache
#      - ipfs
#    networks:
#      - my_network


  my-app-test-1:
    container_name: my-app-test-1
    build:
      dockerfile: Dockerfile
    image: my-app-test:latest
    ports:
        - "21001"
    depends_on:
        - mysql-hp
        - keycloak-hp
        - prometheus
        - node-exporter
        - alert-manager
        - tempo
        - token_retrieval

  my-app-test-2:
    container_name: my-app-test-2
    build:
      dockerfile: Dockerfile
    image: my-app-test:latest
    ports:
        - "21002"
    depends_on:
        - mysql-hp
        - keycloak-hp
        - prometheus
        - node-exporter
        - alert-manager
        - tempo
        - token_retrieval
        - ipfs0
        - cluster0
        - ipfs1
        - cluster1
        - ipfs2
        - cluster2

#    my-app-test-2:
#      container_name: my-app-test-2
#      build:
#        dockerfile: Dockerfile
#      image: my-app-test:latest
#      ports:
#        - "21002:21001"
#      depends_on:
#        - mysql-hp
#        - keycloak-hp
#        - prometheus
#        - node-exporter
#        - alert-manager
#        - tempo
#        - token_retrieval
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile_nginx
    ports:
      - "10000:10000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-app-test-1

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri'
      - 'http://nginx:10000/stub_status'  # Adjusted to match Nginx's listen port
    ports:
      - "9113:9113"
    depends_on:
      - nginx

#----------------------IPFS-------------------------
  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8070:8070" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      # Open API port (allows ipfs-cluster-ctl usage on host)
      - "127.0.0.1:9094:9094"
      # The cluster swarm port would need  to be exposed if this container
      # was to connect to cluster peers on other hosts.
      # But this is just a testing cluster.
      - "9095:9095" # Cluster IPFS Proxy endpoint
      - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster

  ##################################################################################
  ## Cluster PEER 1 ################################################################
  ##################################################################################

  # See Cluster PEER 0 for comments (all removed here and below)
  ipfs1:
    container_name: ipfs1
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs1:/data/ipfs

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster1:/data/ipfs-cluster

  ##################################################################################
  ## Cluster PEER 2 ################################################################
  ##################################################################################

  # See Cluster PEER 0 for comments (all removed here and below)
  ipfs2:
    container_name: ipfs2
    image: ipfs/kubo:release
    volumes:
      - ./compose/ipfs2:/data/ipfs

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster2:/data/ipfs-cluster
#----------------------IPFS-------------------------

volumes:

    mysql_data:
      driver: local
    grafana_data:
      driver: local
    promtail_data:
      driver: local
    tempo_data:
      driver: local
    token_volume:
      driver: local



networks:
  my_network:
    driver: bridge

#this is a test