services:
  mysql:
    image: mysql:8.2
    environment:
      - MYSQL_DATABASE=my-app-test
      - MYSQL_ROOT_PASSWORD=P4ssword!
    ports:
      - 3307:3306
  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:22.0.1
    #build:
    # context: .
    #args:
    # KEYCLOAK_VERSION: 22.0.1
    command:
      - "start-dev"
    ports:
      - "8180:8080"
  #keycloak:
    #image: quay.io/keycloak/keycloak:23.0.4
   # environment:
      #- KEYCLOAK_USER=admin
      #- KEYCLOAK_PASSWORD=admin
    #ports:
      #- 8080:8080

