spring:
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak-hp:8080/realms/myrealm

  datasource:
      url: jdbc:mysql://mysql-hp:3306/my-app-test?serverTimezone=UTC
      username: root
      password: P4ssword!
      dbcp2:
        max-wait-millis: 30000
        validation-query: /* ping */ select 1
        validation-query-timeout: 30
  jpa:
      hibernate:
        ddl-auto: create
      open-in-view: false
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          id:
            new_generator_mappings: true
  #docker:
   # compose:
      #lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**

server:
  port: 21001
  #chamika

management:
  zipkin:
    tracing:
      endpoint: http://my-app-test-tempo-1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health,loggers
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
            include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

#ganache.url=http://localhost:7545
#contract.address=0x806143c64034d7Ad6488d753497F10E04b9C0e3E

ganache:
  url: "http://my-app-test-ganache-1:8545"

contract:
  address: "0xf12b5dd4ead5f743c6baa640b0216200e89b60da"